// import type { Metadata } from "next";

import Header from "./header";

// import { Montserrat } from "next/font/google";

import "../src/globals.css";

// const montserrat = Montserrat({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    <>
      <Header />
      <div className="px-[25px] pb-[20px] lg:px-[40px] xl:px-[60px] 2xl:px-[80px] pt-[84px] lg:pt-[96px] xl:pt-[116px] 2xl:pt-[149px] ">
        {children}
      </div>
    </>
    // </html>
  );
}
